# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=25)),
                ('province', models.CharField(max_length=2)),
                ('postal', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=15)),
                ('no_of_emp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=25)),
                ('province', models.CharField(max_length=2)),
                ('postal', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='Enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise'),
        ),
    ]
