# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-09 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('postal', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='companies',
            name='city',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='country',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='no_of_emp',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='province',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='city',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='country',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='province',
        ),
        migrations.AlterField(
            model_name='companies',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Address'),
        ),
    ]
